
    -- PRACTICA DML-0 --
    
    -- Ejercicio 1 -- 
    SELECT NOMBRE, APELLIDO1, APELLIDO2
    FROM PROFESORES
    WHERE DEPARTAMENTO = 1;
    
    -- Ejercicio 2 --
    SELECT NOMBRE, APELLIDO1, APELLIDO2
    FROM PROFESORES
    WHERE DEPARTAMENTO != 3;
    
    -- Ejercicio 3 --
    SELECT NOMBRE, APELLIDO1, APELLIDO2
    FROM PROFESORES
    WHERE EMAIL LIKE '%lcc.uma.es';
    
        -- DUDA: QUE USOS DARLE ENTRE EL LIKE Y EL =
        -- RESPUESTA: LIKE es el Detective
        --            = es el Dato Exacto
        
    -- Ejercicio 4 --
    SELECT NOMBRE, APELLIDO1, APELLIDO2
    FROM ALUMNOS
    WHERE EMAIL IS NULL;
    
    -- Ejercicio 5 --
    SELECT NOMBRE, CREDITOS, (TEORICOS/CREDITOS)*100, (PRACTICOS/CREDITOS)*100
    FROM ASIGNATURAS
    WHERE CURSO = 3;
    
    -- Ejercicio 6 --
    SELECT ALUMNO, CALIFICACION
    FROM MATRICULAR
    WHERE ASIGNATURA = 112
    ORDER BY ALUMNO;
    
    -- Ejercicio 7 --
    SELECT NOMBRE, HOMBRES+MUJERES
    FROM MUNICIPIO;
    
    -- Ejercicio 8 -- o CONCAT(Arg1,Arg2)...
    SELECT 'El alumno ' || NOMBRE || ' ' || APELLIDO1 || ' ' || APELLIDO2 || ' no dispone de Correo'
    FROM ALUMNOS
    WHERE EMAIL IS NULL;
    
    -- Ejercicio 9 --
    SELECT NOMBRE, APELLIDO1, APELLIDO2
    FROM PROFESORES
    WHERE TO_DATE('01/01/1990', 'DD/MM/YYYY')> ANTIGUEDAD;
    
    -- Ejercicio 10 --
    SELECT NOMBRE, APELLIDO1, APELLIDO2
    FROM PROFESORES
    WHERE MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)<480;
    
    -- Ejercicio 11 --
    SELECT UPPER(NOMBRE||' '||APELLIDO1||' '||APELLIDO2||' ') "NOMBRE Y APELLIDOS",TRUNC(MONTHS_BETWEEN(SYSDATE,ANTIGUEDAD)/36) "TRIENIOS_ACUM"
    FROM PROFESORES
    WHERE TRUNC(MONTHS_BETWEEN(SYSDATE,ANTIGUEDAD)/36)>=3;
    
    -- Ejercicio 12 --
    SELECT REPLACE(NOMBRE,'Bases de Datos','Almacenes de Datos') "ALMACENES DE DATOS"
    FROM ASIGNATURAS
    WHERE NOMBRE LIKE '%Bases de Datos%';
    
    -- Ejercicio 13 --
    SELECT NOMBRE, NVL(TO_CHAR(CREDITOS),'No asignado')
    FROM ASIGNATURAS
    WHERE CARACTER LIKE 'O_';
    
    -- Ejercicio 14 --
    SELECT NOMBRE, APELLIDO1, APELLIDO2 
    FROM ALUMNOS
    WHERE MONTHS_BETWEEN(SYSDATE,FECHA_PRIM_MATRICULA)<24;
    
    -- Ejercicio 15 --
    SELECT NOMBRE, APELLIDO1, APELLIDO2 
    FROM ALUMNOS
    WHERE MONTHS_BETWEEN(FECHA_PRIM_MATRICULA,FECHA_NACIMIENTO)<216;
    
    -- Ejercicio 16 --
    SELECT NOMBRE, APELLIDO1, APELLIDO2 
    FROM ALUMNOS
    WHERE TO_CHAR(FECHA_PRIM_MATRICULA,'fmDAY')='LUNES';
